# Build and deploy future-helper
cache:
  paths:
    - .m2/
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
    - test
    - build
    - deploy
    - s3

test-jdk-8:
  stage: test
  image: maven:3-jdk-8-slim
  script:
    - mvn -B test

test-jdk-9:
  stage: test
  image: maven:3-jdk-9-slim
  script:
    - mvn -B test

test-jdk-10:
  stage: test
  image: maven:3-jdk-10-slim
  script:
    - mvn -B test

test-jdk-11:
  stage: test
  image: maven:3-jdk-11-slim
  script:
    - mvn -B test

test-jdk-12:
  stage: test
  image: maven:3-jdk-12-slim
  script:
    - mvn -B test

test-jdk-13:
  stage: test
  image: maven:3-jdk-13-slim
  script:
    - mvn -B test

package:
  stage: build
  script:
    - mvn -B package
  artifacts:
    paths:
    - target
  image: maven
  
  
deploy:
  stage: deploy
  script:
    - mvn -B -DaltDeploymentRepository=repo::default::file:./target/staging deploy
#    - cp target/future-helper-*-fat.jar target/staging/io/cloudonix/future-helper/*/
  artifacts:
    paths:
    - target/staging
  image: maven

s3:
  stage: s3
  image:
    name: mesosphere/aws-cli
    entrypoint: [""]
  script:
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/releases
  only:
    - master
