# Build and deploy future-helper
cache:
  paths:
    - .m2/
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
    - test
    - build
    - deploy
    - s3

test-jdk-8:
  stage: test
  needs: []
  image: maven:3-amazoncorretto-8
  script:
    - mvn -B test

test-jdk-11:
  stage: test
  needs: []
  image: maven:3-amazoncorretto-11
  script:
    - mvn -B test

test-jdk-17:
  stage: test
  needs: []
  image: maven:3-amazoncorretto-17
  script:
    - mvn -B test

test-jdk-19:
  stage: test
  needs: []
  image: maven:3-amazoncorretto-19
  script:
    - mvn -B test

test-jdk-20:
  stage: test
  needs: []
  image: maven:3-amazoncorretto-20
  script:
    - mvn -B test

test-jdk-21:
  stage: test
  needs: []
  image: maven:3-amazoncorretto-21
  script:
    - mvn -B test

package:
  stage: build
  needs: []
  image: maven
  script:
    - mvn -B -DskipTests package
  artifacts:
    paths:
      - target
  
deploy:maven:
  stage: deploy
  needs: [ package ]
  image: maven
  script:
   - mvn -B -s ci-settings.xml -DskipTests -Dmaven.gpg.skip=true deploy
  rules:
    - if: $CI_COMMIT_TAG

deploy:
  stage: deploy
  needs: [ package ]
  image: maven
  script:
    - mvn -B -DskipTests -DaltDeploymentRepository=repo::default::file:./target/staging deploy
#    - cp target/future-helper-*-fat.jar target/staging/io/cloudonix/future-helper/*/
  artifacts:
    paths:
      - target/staging
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

s3:
  stage: s3
  needs: [ deploy ]
  image:
    name: mesosphere/aws-cli
    entrypoint: [""]
  script:
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/releases
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
